$(document).ready(function(){
  $("#web").click(function(){
      $("#web-part").show();
      $("#mobile-part").hide();
      $("#desktop-part").hide();
      $("#design-part").hide();
  });
  $("#mobile").click(function(){
      $("#web-part").hide();
      $("#mobile-part").show();
      $("#desktop-part").hide();
      $("#design-part").hide();
  });
  $("#desktop").click(function(){
      $("#web-part").hide();
      $("#mobile-part").hide();
      $("#desktop-part").show();
      $("#design-part").hide();
  });
  $("#design").click(function(){
      $("#web-part").hide();
      $("#mobile-part").hide();
      $("#desktop-part").hide();
      $("#design-part").show();
  });
});

$(document).ready(function () {
    $('.owl-carousel-header').owlCarousel({
    loop:true,
    margin:10,
    autoplayTimeout:10000,
    nav:true,
    autoplay:true,
    responsive:{
        0:{
            items:1
        },
        600:{
            items:1
        },
        1000:{
            items:1
        }
    }
    })
});